### ISSUE TITLE
sqlite3.OperationalError: no such table: tbl

### ISSUE THREAD

**Issue by IXEguy** [tobimensch/termsql#1]
When I execute the following

```
termsql -i ../DEREG.txt -t Deregistered -d',' -1 -o FAA.db --max-rows=10 -D
```

It gets to the part where it creates the database file (if needed) and the table & columns from the first row..but before any data is inserted, it returns the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/termsql", line 357, in <module>
    c.executemany('insert into tbl values ('+placeholder_str+')', inserts)
sqlite3.OperationalError: no such table: tbl
```

**Comment by IXEguy** [comment]
Just wanted to come back & mention that I resolved this issue by making the following update to line 357

```
c.executemany('insert into '+table_name+' values ('+placeholder_str+')', inserts)
```

**Comment by tobimensch** [comment]
Thanks for reporting this. Will commit the fix soon.

**Comment by IXEguy** [comment]
No problem. I submitted a pull request too, I hope I did it right!

**Comment by tobimensch** [comment]
The fix is commited. Closing this issue.
