### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by saaj** [tobimensch/termsql#12]
Do you have plans to release the package on PyPI any time soon?

**Comment by tobimensch** [comment]
I'd definitely like to. flint seems a good way to achieve it. If anyone wants to help me with this, you're welcome.

**Comment by tobimensch** [comment]
@saaj 
I had an annoying issue where pypi didn't accept an rst file I converted from the markdown README. After resolving that by removing parts of the file, termsql can now finally be installed form pypi.

pip3 install termsql

should work!

Please try it and report if it's working, if not reopen this issue.
