### ISSUE TITLE
Text deliminator

### ISSUE THREAD

**Issue by js333031** [tobimensch/termsql#9]
I have a csv file where some cells contain text string, like the example below.

Three cells:
`previous cell data, "abcd, efg", next cell data`

The second column has a quoted string with comma as part of the text. This causes termsql to create 4 columns where 2nd column is `"abcd` and 3rd column is `efg"`

Is there an termsql option that can use both the cell deliminator and text deliminator?

**Comment by tobimensch** [comment]
There's an option for using regex as a delimiter. (-g) Though possible, I guess it's not trivial to develop the correct regex for splitting a csv line with quoted strings.

I just added a new option (--csv) to termsql. If you use that, termsql uses python's csv parser using `"` as the quote char and `,` as the delimiter. You can still change the delimiter to something else if you like though.
